UPDATE propiedades SET nombre = 'Beruti 2856', direccion = 'Beruti 2856, Cdad. Autónoma de Buenos Aires' WHERE id = '10001';
UPDATE propiedades SET nombre = 'Cabildo 250', direccion = 'Avenida Cabildo 250, Cdad. Autónoma de Buenos Aires' WHERE id = '10002';
UPDATE propiedades SET nombre = 'Peru 666', direccion = 'Peru 666, Cdad. Autónoma de Buenos Aires' WHERE id = '10003';
UPDATE propiedades SET nombre = 'Moldes 2185', direccion = 'Moldes 2185, Cdad. Autónoma de Buenos Aires' WHERE id = '10004';
UPDATE propiedades SET nombre = 'Frias 149', direccion = 'Tte. Gral. Eustoquio Frías 149, Cdad. Autónoma de Buenos Aires' WHERE id = '10005';
UPDATE propiedades SET nombre = 'Casa Altos', direccion = 'Alborado S/N y, Ruta 25, B1627 Matheu' WHERE id = '10006';
UPDATE propiedades SET nombre = 'Viamonte 2534', direccion = 'Viamonte 2534, Cdad. Autónoma de Buenos Aires' WHERE id = '10007';
UPDATE propiedades SET nombre = 'Bartolomé Mitre 1800', direccion = 'Bartolomé Mitre 1800, C1039 Cdad. Autónoma de Buenos Aires, Argentina' WHERE id = '10008';
UPDATE propiedades SET nombre = 'Elcano 3654 (alquiler)', direccion = 'Avenida Elcano 3654, Cdad. Autónoma de Buenos Aires' WHERE id = '10009';
UPDATE propiedades SET nombre = 'Conesa 2117', direccion = 'Conesa 2117, C1428CUG Cdad. Autónoma de Buenos Aires' WHERE id = '10010';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10011';
UPDATE propiedades SET nombre = 'Beruti 2856 5C (alquiler)', direccion = 'Beruti 2856, Cdad. Autónoma de Buenos Aires' WHERE id = '10012';
UPDATE propiedades SET nombre = 'Guemes 3355', direccion = 'Güemes 3355, C1425 Cdad. Autónoma de Buenos Aires' WHERE id = '10013';
UPDATE propiedades SET nombre = 'Paraguay 4445 3 203', direccion = 'Paraguay 4445, C1425 Cdad. Autónoma de Buenos Aires' WHERE id = '10014';
UPDATE propiedades SET nombre = 'Mario Bravo 1150', direccion = 'Mario Bravo 1150, C1175ABV Cdad. Autónoma de Buenos Aires' WHERE id = '10015';
UPDATE propiedades SET nombre = 'Costa Rica 4409', direccion = 'Costa Rica 4409, C1414BSE Cdad. Autónoma de Buenos Aires' WHERE id = '10016';
UPDATE propiedades SET nombre = 'Arcos 2825', direccion = 'Agüero 1945, Cdad. Autónoma de Buenos Aires' WHERE id = '10017';
UPDATE propiedades SET nombre = 'Esmeralda 1375', direccion = 'Esmeralda 1375, Cdad. Autónoma de Buenos Aires' WHERE id = '10018';
UPDATE propiedades SET nombre = 'Ruy Diaz de Guzman 107', direccion = 'Ruy Díaz de Guzmán 107, Buenos Aires' WHERE id = '10019';
UPDATE propiedades SET nombre = 'Galeria Internacional Corrientes 2322', direccion = NULL WHERE id = '10020';
UPDATE propiedades SET nombre = 'Corrientes 2322', direccion = 'Av. Corrientes 2322, Cdad. Autónoma de Buenos Aires' WHERE id = '10021';
UPDATE propiedades SET nombre = 'Teodoro García 3724', direccion = 'Teodoro García 3724, C1427ECF Cdad. Autónoma de Buenos Aires' WHERE id = '10022';
UPDATE propiedades SET nombre = 'Haras del Sur', direccion = 'Km. 69, Ruta Provincial 2, 1900 La Plata, Provincia de Buenos Aires' WHERE id = '10023';
UPDATE propiedades SET nombre = 'Uruguay 1134', direccion = 'Uruguay 1134, Cdad. Autónoma de Buenos Aires' WHERE id = '10024';
UPDATE propiedades SET nombre = 'Uruguay 1134', direccion = 'Uruguay 1134, Cdad. Autónoma de Buenos Aires' WHERE id = '10025';
UPDATE propiedades SET nombre = 'Arenales 1391', direccion = NULL WHERE id = '10026';
UPDATE propiedades SET nombre = 'Terreno 12 de Octubre 695', direccion = '12 de Octubre 695, Dock Sud' WHERE id = '10027';
UPDATE propiedades SET nombre = 'Salta 1990', direccion = 'Salta 1990, Gerli, Avellaneda' WHERE id = '10028';
UPDATE propiedades SET nombre = 'Agüero 1945', direccion = 'Agüero 1945, Cdad. Autónoma de Buenos Aires' WHERE id = '10029';
UPDATE propiedades SET nombre = 'Baigorria 2400', direccion = 'Baigorria 2400, C1417FQC Cdad. Autónoma de Buenos Aires' WHERE id = '10030';
UPDATE propiedades SET nombre = 'Talcahuano 1097', direccion = NULL WHERE id = '10031';
UPDATE propiedades SET nombre = 'Uruguay 1136', direccion = 'Uruguay 1136, Cdad. Autónoma de Buenos Aires' WHERE id = '10032';
UPDATE propiedades SET nombre = 'Independencia 1248', direccion = 'Independencia 1248, Cdad. Autónoma de Buenos Aires' WHERE id = '10033';
UPDATE propiedades SET nombre = 'Santa María de Tigre', direccion = NULL WHERE id = '10034';
UPDATE propiedades SET nombre = 'Uruguay 1143 PB', direccion = 'Uruguay 1143, Cdad. Autónoma de Buenos Aires' WHERE id = '10035';
UPDATE propiedades SET nombre = 'Uruguay 1134 3ro "C"', direccion = 'Uruguay 1134, Cdad. Autónoma de Buenos Aires' WHERE id = '10036';
UPDATE propiedades SET nombre = 'Cordoba 5096', direccion = 'Córdoba 5096, Cdad. Autónoma de Buenos Aires' WHERE id = '10037';
UPDATE propiedades SET nombre = 'Cordoba 966', direccion = 'Córdoba 966, Cdad. Autónoma de Buenos Aires' WHERE id = '10038';
UPDATE propiedades SET nombre = 'Cuba 2370', direccion = 'Cuba 2370, Cdad. Autónoma de Buenos Aires' WHERE id = '10039';
UPDATE propiedades SET nombre = 'La Faustina', direccion = 'Km 76,6, RP2, Coronel Brandsen, Provincia de Buenos Aires' WHERE id = '10040';
UPDATE propiedades SET nombre = 'Diaz Velez 3888', direccion = NULL WHERE id = '10041';
UPDATE propiedades SET nombre = 'Perito Moreno 300 (Neuquen)', direccion = NULL WHERE id = '10042';
UPDATE propiedades SET nombre = 'Rivadavia 5594', direccion = 'Rivadavia 5594, Cdad. Autónoma de Buenos Aires' WHERE id = '10043';
UPDATE propiedades SET nombre = 'Santa Fe 1834', direccion = NULL WHERE id = '10044';
UPDATE propiedades SET nombre = 'Roosevelt 1769', direccion = 'Franklin D. Roosevelt 1769, C1428BNE Cdad. Autónoma de Buenos Aires' WHERE id = '10045';
UPDATE propiedades SET nombre = 'Uruguay 1133', direccion = 'Uruguay 1133, Cdad. Autónoma de Buenos Aires' WHERE id = '10046';
UPDATE propiedades SET nombre = 'Esmeralda 909', direccion = 'Esmeralda 909, Cdad. Autónoma de Buenos Aires' WHERE id = '10047';
UPDATE propiedades SET nombre = 'Parana 1033', direccion = NULL WHERE id = '10048';
UPDATE propiedades SET nombre = 'Elcano 3654', direccion = 'Avenida Elcano 3654, Cdad. Autónoma de Buenos Aires' WHERE id = '10049';
UPDATE propiedades SET nombre = 'Curapaligue 1265', direccion = NULL WHERE id = '10050';
UPDATE propiedades SET nombre = 'Malabia 1141', direccion = NULL WHERE id = '10051';
UPDATE propiedades SET nombre = 'Avellaneda 2049', direccion = 'Avellaneda 2049, Cdad. Autónoma de Buenos Aires' WHERE id = '10052';
UPDATE propiedades SET nombre = 'Uruguay 1143 5to "B"', direccion = 'Uruguay 1143, Cdad. Autónoma de Buenos Aires' WHERE id = '10053';
UPDATE propiedades SET nombre = 'Mario Bravo 1150 2do "B"', direccion = NULL WHERE id = '10054';
UPDATE propiedades SET nombre = 'Aguilar 2144 5to "A"', direccion = NULL WHERE id = '10055';
UPDATE propiedades SET nombre = 'Billinghurst 2424 3ro "A"', direccion = NULL WHERE id = '10056';
UPDATE propiedades SET nombre = 'Freire 2443 ', direccion = NULL WHERE id = '10057';
UPDATE propiedades SET nombre = 'San Martin 2735 (Lanús)', direccion = NULL WHERE id = '10058';
UPDATE propiedades SET nombre = 'Gorriti 6066', direccion = 'Gorriti 6066, Cdad. Autónoma de Buenos Aires' WHERE id = '10059';
UPDATE propiedades SET nombre = 'Juan Bautista Alberdi 4711', direccion = NULL WHERE id = '10060';
UPDATE propiedades SET nombre = 'Arismendi 2468', direccion = NULL WHERE id = '10061';
UPDATE propiedades SET nombre = 'Austria 1958', direccion = NULL WHERE id = '10062';
UPDATE propiedades SET nombre = 'Paraguay 4445 11 "03"', direccion = NULL WHERE id = '10063';
UPDATE propiedades SET nombre = 'Arenales 2225', direccion = NULL WHERE id = '10064';
UPDATE propiedades SET nombre = 'Ferre 245 (Sarandí)', direccion = NULL WHERE id = '10065';
UPDATE propiedades SET nombre = 'Guemes 3456', direccion = NULL WHERE id = '10066';
UPDATE propiedades SET nombre = 'AIRBNB - Beruti 2856 (Alquiler temporario)', direccion = 'Beruti 2856, Cdad. Autónoma de Buenos Aires' WHERE id = '10067';
UPDATE propiedades SET nombre = 'Calle 22 nro 248 (La Plata)', direccion = 'C. 22 248, B1902DBJ La Plata, Provincia de Buenos Aires' WHERE id = '10068';
UPDATE propiedades SET nombre = 'José Pedro Varela 4447', direccion = 'José Pedro Varela 4447, Cdad. Autónoma de Buenos Aires' WHERE id = '10069';
UPDATE propiedades SET nombre = 'Paraguay 5259', direccion = NULL WHERE id = '10070';
UPDATE propiedades SET nombre = 'Corrientes 1719', direccion = 'Av. Corrientes 1719, Cdad. Autónoma de Buenos Aires, Argentina' WHERE id = '10071';
UPDATE propiedades SET nombre = 'Cátulo Castillo 2975 2do "A"', direccion = NULL WHERE id = '10072';
UPDATE propiedades SET nombre = 'República Árabe Siria 2693', direccion = 'República Árabe Siria 2693, Cdad. Autónoma de Buenos Aires' WHERE id = '10073';
UPDATE propiedades SET nombre = 'Tomás Le Bretón 2900', direccion = NULL WHERE id = '10074';
UPDATE propiedades SET nombre = 'Carlos Calvo 3000', direccion = NULL WHERE id = '10075';
UPDATE propiedades SET nombre = 'Cerrito 1100', direccion = NULL WHERE id = '10076';
UPDATE propiedades SET nombre = 'Barrio Venice, Tigre (Alquiler)', direccion = 'Bourdieu 543, Tigre, Provincia de Buenos Aires' WHERE id = '10077';
UPDATE propiedades SET nombre = 'Malabia 2188', direccion = NULL WHERE id = '10078';
UPDATE propiedades SET nombre = 'República Árabe Siria 2749 1ro "A"', direccion = 'República Árabe Siria 2749, Cdad. Autónoma de Buenos Aires' WHERE id = '10079';
UPDATE propiedades SET nombre = 'Corrientes 4028', direccion = 'Av. Corrientes 4028, Cdad. Autónoma de Buenos Aires' WHERE id = '10080';
UPDATE propiedades SET nombre = '11 de Septiembre 2275', direccion = '11 de Septiembre de 1888 2275, Cdad. Autónoma de Buenos Aires' WHERE id = '10081';
UPDATE propiedades SET nombre = 'Thames 306', direccion = 'Thames 306, Cdad. Autónoma de Buenos Aires' WHERE id = '10082';
UPDATE propiedades SET nombre = 'Pestalozzi 3560', direccion = 'Pestalozzi 3560, Cdad. Autónoma de Buenos Aires' WHERE id = '10083';
UPDATE propiedades SET nombre = 'AIRBNB - Córdoba 966', direccion = 'Córdoba 966, Cdad. Autónoma de Buenos Aires' WHERE id = '10084';
UPDATE propiedades SET nombre = 'Coronel Diaz 2561', direccion = NULL WHERE id = '10085';
UPDATE propiedades SET nombre = 'La Rioja 1104', direccion = 'La Rioja 1104, Cdad. Autónoma de Buenos Aires' WHERE id = '10086';
UPDATE propiedades SET nombre = 'Cerrito 36', direccion = NULL WHERE id = '10087';
UPDATE propiedades SET nombre = 'Amenabar 2667', direccion = NULL WHERE id = '10088';
UPDATE propiedades SET nombre = 'Frias 149', direccion = NULL WHERE id = '10089';
UPDATE propiedades SET nombre = 'Ricardo Gutiérrez 2260', direccion = 'Ricardo Gutiérrez 2260, Olivos' WHERE id = '10090';
UPDATE propiedades SET nombre = 'Lavalle 1567, 2°210 y 211 VENTA', direccion = 'Lavalle 1567, Cdad. Autónoma de Buenos Aires' WHERE id = '10091';
UPDATE propiedades SET nombre = 'Lavalle 1567, 2°211 (Alquiler)', direccion = 'Lavalle 1567, Cdad. Autónoma de Buenos Aires' WHERE id = '10092';
UPDATE propiedades SET nombre = 'San Pedrito 8', direccion = 'San Pedrito 8, Cdad. Autónoma de Buenos Aires' WHERE id = '10093';
UPDATE propiedades SET nombre = 'Av. San Isidro 4179', direccion = NULL WHERE id = '10094';
UPDATE propiedades SET nombre = 'Uriburu 600', direccion = NULL WHERE id = '10095';
UPDATE propiedades SET nombre = 'Pueyrredón 2434', direccion = 'Av. Pueyrredón 2434, Cdad. Autónoma de Buenos Aires' WHERE id = '10096';
UPDATE propiedades SET nombre = 'Pasco 1512', direccion = NULL WHERE id = '10097';
UPDATE propiedades SET nombre = 'Juana Manso 1113', direccion = NULL WHERE id = '10098';
UPDATE propiedades SET nombre = 'Bellaustegui 2822', direccion = NULL WHERE id = '10099';
UPDATE propiedades SET nombre = 'Arenales 903', direccion = NULL WHERE id = '10100';
UPDATE propiedades SET nombre = 'Juan de Garay 2525 (Olivos)', direccion = NULL WHERE id = '10101';
UPDATE propiedades SET nombre = 'Juan de Garay 2525 (Olivos)', direccion = NULL WHERE id = '10102';
UPDATE propiedades SET nombre = 'Loma Verde', direccion = 'Colectora Oeste Ramal Escobar, RN9 Km 56.5, B1625 Belén de Escobar, Provincia de Buenos Aires' WHERE id = '10103';
UPDATE propiedades SET nombre = 'Tacuarí 1078', direccion = 'Tacuarí 1078, Cdad. Autónoma de Buenos Aires' WHERE id = '10104';
UPDATE propiedades SET nombre = 'Paraguay 2600 (Marcela)', direccion = 'Paraguay 2600, C1425BRB Cdad. Autónoma de Buenos Aires' WHERE id = '10105';
UPDATE propiedades SET nombre = 'Villanueva 1145', direccion = 'Villanueva 1145, Cdad. Autónoma de Buenos Aires' WHERE id = '10106';
UPDATE propiedades SET nombre = 'Uruguay 973 9°A', direccion = 'Uruguay 973, Cdad. Autónoma de Buenos Aires' WHERE id = '10107';
UPDATE propiedades SET nombre = 'Uruguay 1279 (Marcela)', direccion = 'Uruguay 1279, Cdad. Autónoma de Buenos Aires' WHERE id = '10108';
UPDATE propiedades SET nombre = 'Amenabar 3851', direccion = 'Amenábar 3851, Buenos Aires' WHERE id = '10109';
UPDATE propiedades SET nombre = 'Paraguay 5449 5C', direccion = 'Paraguay 5449, C1425BTK C1425BTN, Buenos Aires' WHERE id = '10110';
UPDATE propiedades SET nombre = 'Gurruchaga 2189 3A', direccion = 'Gurruchaga 2189, C1425FEE Cdad. Autónoma de Buenos Aires' WHERE id = '10111';
UPDATE propiedades SET nombre = 'Aqua Tempora', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10112';
UPDATE propiedades SET nombre = 'Armenia 2187', direccion = 'Armenia 2187, C1425FBC Cdad. Autónoma de Buenos Aires' WHERE id = '10113';
UPDATE propiedades SET nombre = 'Cuba 2696', direccion = 'Cuba 2696, Cdad. Autónoma de Buenos Aires' WHERE id = '10114';
UPDATE propiedades SET nombre = 'Local Arcos 2391', direccion = 'Arcos 2391, Cdad. Autónoma de Buenos Aires' WHERE id = '10115';
UPDATE propiedades SET nombre = 'Zabala 3556 (Depto hijo Tito)', direccion = 'Zabala 3556, C1427DYB Cdad. Autónoma de Buenos Aires' WHERE id = '10116';
UPDATE propiedades SET nombre = 'Parera 36', direccion = 'Parera 36, C1014ABB Cdad. Autónoma de Buenos Aires' WHERE id = '10117';
UPDATE propiedades SET nombre = 'Montevideo 1566', direccion = 'Montevideo 1566, C1018ACH Cdad. Autónoma de Buenos Aires' WHERE id = '10118';
UPDATE propiedades SET nombre = 'Cordoba 1336 9no "35"', direccion = 'Av. Córdoba 1336, C1055 San Nicolas, Buenos Aires' WHERE id = '10119';
UPDATE propiedades SET nombre = 'Roosevelt 1681', direccion = 'Franklin D. Roosevelt 1600, C1428BNB Cdad. Autónoma de Buenos Aires' WHERE id = '10120';
UPDATE propiedades SET nombre = 'Darragueyra 2449', direccion = 'Darregueyra 2449, Buenos Aires' WHERE id = '10121';
UPDATE propiedades SET nombre = 'Ayacucho 2168 11vo "A"', direccion = 'Ayacucho 2168, C1112 Cdad. Autónoma de Buenos Aires' WHERE id = '10122';
UPDATE propiedades SET nombre = 'Callao 1188 1er Piso', direccion = 'Av. Callao 1188, C1023AAR Cdad. Autónoma de Buenos Aires' WHERE id = '10123';
UPDATE propiedades SET nombre = 'Callao 1200', direccion = 'Av. Callao 1200, C1023AAR Cdad. Autónoma de Buenos Aires' WHERE id = '10124';
UPDATE propiedades SET nombre = 'Paraguay 4445 "205"', direccion = 'Paraguay 4445, C1425 Cdad. Autónoma de Buenos Aires' WHERE id = '10125';
UPDATE propiedades SET nombre = 'Terreno Laprida 745', direccion = 'Francisco N. de Laprida 745, B1638CRG Vicente López, Provincia de Buenos Aires' WHERE id = '10126';
UPDATE propiedades SET nombre = 'Arenales 2024 (AIRBNB)', direccion = 'Arenales 2024, C1124AAE Cdad. Autónoma de Buenos Aires' WHERE id = '10127';
UPDATE propiedades SET nombre = 'Uruguay 356', direccion = 'Uruguay 356, C1015 San Nicolas, Buenos Aires' WHERE id = '10128';
UPDATE propiedades SET nombre = 'Le Breton 5028', direccion = 'Tomás A. Le Bretón 5428, Buenos Aires' WHERE id = '10129';
UPDATE propiedades SET nombre = 'Humboldt 1428 Piso 7', direccion = 'Humboldt 1428, Buenos Aires' WHERE id = '10130';
UPDATE propiedades SET nombre = 'Boyacá 1732', direccion = 'Comuna 11, Boyacá 1732, C1416AAN Cdad. Autónoma de Buenos Aires' WHERE id = '10131';
UPDATE propiedades SET nombre = 'Moldes 1865 4to "A"', direccion = 'Moldes 1865, C1426 Cdad. Autónoma de Buenos Aires' WHERE id = '10132';
UPDATE propiedades SET nombre = 'AIRBNB - Roosevelt 2177 Piso 2 "202"', direccion = 'Franklin D. Roosevelt 2177, C1428BOE Cdad. Autónoma de Buenos Aires' WHERE id = '10133';
UPDATE propiedades SET nombre = 'AIRBNB - Corrientes 951 6D', direccion = 'Av. Corrientes 951, C1043AAJ Cdad. Autónoma de Buenos Aires' WHERE id = '10134';
UPDATE propiedades SET nombre = 'Humboldt 1428 1ro "A"', direccion = 'Humboldt 1428, Buenos Aires' WHERE id = '10135';
UPDATE propiedades SET nombre = 'Búsqueda Delia', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10136';
UPDATE propiedades SET nombre = 'Búsqueda Tassara', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10137';
UPDATE propiedades SET nombre = 'Búsqueda Gárcia', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10138';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 216 (FraS)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10139';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 312 (MS)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10140';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 316 (FS)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10141';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 414 (VS)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10142';
UPDATE propiedades SET nombre = 'AIRBNB - Esmeralda (Masini)', direccion = 'Esmeralda 827, Cdad. Autónoma de Buenos Aires' WHERE id = '10143';
UPDATE propiedades SET nombre = 'Leiva 3600', direccion = 'Leiva 3600, C1427EMB Cdad. Autónoma de Buenos Aires' WHERE id = '10144';
UPDATE propiedades SET nombre = 'Ramón Falcon 4900 (otra inmobiliaria hasta Dic)', direccion = 'Cnel. Ramón L. Falcón 4900, C1408 Cdad. Autónoma de Buenos Aires' WHERE id = '10145';
UPDATE propiedades SET nombre = 'Vidal 1844', direccion = 'Vidal 1844, C1428 Cdad. Autónoma de Buenos Aires' WHERE id = '10146';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 211 (Fernando Nievas)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10147';
UPDATE propiedades SET nombre = 'La Plata Calle 236', direccion = 'Arturo Seguí, Provincia de Buenos Aires' WHERE id = '10148';
UPDATE propiedades SET nombre = 'Dorrego 940', direccion = 'Av. Dorrego 940, C1414CKR Buenos Aires' WHERE id = '10149';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 208 (Maximiliano Cascon) ', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10150';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 407 (Maximiliano Cascon) ', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10151';
UPDATE propiedades SET nombre = 'Busqueda Meli', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10152';
UPDATE propiedades SET nombre = 'Fray Justo Santa Maria de Oro 2631 6TO “B”', direccion = 'Fray Justo Sta. María de Oro 2631 6to b, C1425FOM Cdad. Autónoma de Buenos Aires' WHERE id = '10153';
UPDATE propiedades SET nombre = 'Casa La Damasia (ASESOR GENCO)', direccion = 'Ex Combatiente Juan C. Reguera 1899, B1645 San Fernando, Provincia de Buenos Aires' WHERE id = '10154';
UPDATE propiedades SET nombre = 'Casa Pilar del Este (ASESOR GENCO)', direccion = 'Silverio Basabe 1500, B1627 Zelaya, Provincia de Buenos Aires' WHERE id = '10155';
UPDATE propiedades SET nombre = 'Zapiola 3243 - depto 5', direccion = 'Zapiola 3243, Cdad. Autónoma de Buenos Aires' WHERE id = '10156';
UPDATE propiedades SET nombre = '3 de Febrero 2149 4°B', direccion = '3 de Febrero 2149, Cdad. Autónoma de Buenos Aires' WHERE id = '10157';
UPDATE propiedades SET nombre = 'Chile 943 5°C', direccion = 'Chile 943, Cdad. Autónoma de Buenos Aires' WHERE id = '10158';
UPDATE propiedades SET nombre = 'Busqueda Miguel (amigo Tassara)', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10159';
UPDATE propiedades SET nombre = 'De La Cárcova 3530, 4to "C"', direccion = 'De la Cárcova 3530, C1174 Cdad. Autónoma de Buenos Aires' WHERE id = '10160';
UPDATE propiedades SET nombre = 'Av. Del Libertador 774 3ro "T"', direccion = 'Av. del Libertador 774, C1001 Cdad. Autónoma de Buenos Aires' WHERE id = '10161';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 401 (Verónica Re)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10162';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 402 (Verónica Re)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10163';
UPDATE propiedades SET nombre = 'AIRBNB - Aqua Tempora 415 (Verónica Re)', direccion = 'Montañeses 2342, CP 1429 Cdad. Autónoma de Buenos Aires' WHERE id = '10164';
UPDATE propiedades SET nombre = 'Av. Coronel Cárdenas 2694', direccion = 'Av. Coronel Cárdenas 2694, C1440EJP Buenos Aires' WHERE id = '10165';
UPDATE propiedades SET nombre = 'Cuba 2370 5to  A ', direccion = 'Cuba 2370, Cdad. Autónoma de Buenos Aires' WHERE id = '10166';
UPDATE propiedades SET nombre = 'Casa Nordelta', direccion = 'Lote 238 Barrio Tipas, Nordelta' WHERE id = '10167';
UPDATE propiedades SET nombre = 'Busqueda Graciela (mamá Hernan)', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10168';
UPDATE propiedades SET nombre = 'Búsqueda Poblo', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10169';
UPDATE propiedades SET nombre = 'Av San Juan 1551', direccion = 'Av. San Juan 1551, C1148AAD Cdad. Autónoma de Buenos Aires' WHERE id = '10170';
UPDATE propiedades SET nombre = 'José Hernandez 2342', direccion = 'José Hernández 2342, C1426EOP Cdad. Autónoma de Buenos Aires' WHERE id = '10171';
UPDATE propiedades SET nombre = 'Suarez 1413', direccion = 'Av. Suárez 1413, C1288AEE Cdad. Autónoma de Buenos Aires' WHERE id = '10172';
UPDATE propiedades SET nombre = 'Juan Bautista Alberdi 574', direccion = 'Av. Juan Bautista Alberdi 574 C1424 Cdad. de Buenos Aires' WHERE id = '10173';
UPDATE propiedades SET nombre = 'Vilela 2152', direccion = 'Vilela 2152 C1429DAF Cdad. de Buenos Aires' WHERE id = '10174';
UPDATE propiedades SET nombre = 'Dean Funes 855', direccion = 'Dean Funes 855 C11231ABG Cdad. de Buenos Aires' WHERE id = '10175';
UPDATE propiedades SET nombre = 'Tucuman 766 (Alquiler Temporal)', direccion = 'Tucumán 766, C1049AAP Cdad. Autónoma de Buenos Aires' WHERE id = '10176';
UPDATE propiedades SET nombre = 'Viamonte 741', direccion = 'Viamonte 741, C1053ABO Cdad. Autónoma de Buenos Aires' WHERE id = '10177';
UPDATE propiedades SET nombre = 'AIRBNB - Salta 1188 4to "B"', direccion = 'Salta 1188, C1074AAX Cdad. Autónoma de Buenos Aires' WHERE id = '10178';
UPDATE propiedades SET nombre = 'Humbolt 1428', direccion = 'Humboldt 1428, Cdad. Autónoma de Buenos Aires' WHERE id = '10179';
UPDATE propiedades SET nombre = 'Búsqueda Alejandro', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10180';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10181';
UPDATE propiedades SET nombre = 'Amenabar 1528', direccion = 'Amenábar 1528, C1426AKD Cdad. Autónoma de Buenos Aires' WHERE id = '10182';
UPDATE propiedades SET nombre = 'Santa Fé 2829', direccion = 'Av. Santa Fé 2829, Recoleta, C1425BGP' WHERE id = '10183';
UPDATE propiedades SET nombre = 'J. Salguero 1496', direccion = 'Jerónimo Salguero 1496, C1177AFB Cdad. Autónoma de Buenos Aires' WHERE id = '10184';
UPDATE propiedades SET nombre = 'Anchorena 1192 7°', direccion = 'Dr. Tomás Manuel de Anchorena 1192, C1425 ELB, Cdad. Autónoma de Buenos Aires' WHERE id = '10185';
UPDATE propiedades SET nombre = 'Amenabar 2667 1°B', direccion = 'Amenábar 2667, C1428CQQ Cdad. Autónoma de Buenos Aires' WHERE id = '10186';
UPDATE propiedades SET nombre = 'Búsqueda Dueño Dean Funes', direccion = 'Av. Córdoba 807, C1054AAH Cdad. Autónoma de Buenos Aires' WHERE id = '10187';
UPDATE propiedades SET nombre = 'Libertador 4444', direccion = 'Av. del Libertador 4444, C1426BWS Cdad. Autónoma de Buenos Aires' WHERE id = '10188';
UPDATE propiedades SET nombre = 'AIRBNB - Díaz Vélez 4170 4°C (Alquiler Temp)', direccion = 'Av. Díaz Vélez 4170, C1200AAV Cdad. Autónoma de Buenos Aires' WHERE id = '10189';
UPDATE propiedades SET nombre = 'AIRBNB - Juncal 1681 6°B (Alquiler Temp)', direccion = 'Juncal 1681, C1062 Cdad. Autónoma de Buenos Aires' WHERE id = '10190';
UPDATE propiedades SET nombre = 'Búsqueda Nardo (Bernardo)', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10191';
UPDATE propiedades SET nombre = 'Tacuarí 2069 3ro A', direccion = 'Tacuarí 2069, C1139AAQ Cdad. Autónoma de Buenos Aires' WHERE id = '10192';
UPDATE propiedades SET nombre = 'Austria 1754, 6°', direccion = 'Austria 1754, CABA' WHERE id = '10193';
UPDATE propiedades SET nombre = 'Bolivar 1601, Ramos Mejia', direccion = 'Bolivar 1601, Ramos Mejia' WHERE id = '10194';
UPDATE propiedades SET nombre = 'Búsqueda Norma Haber (Tito)', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10195';
UPDATE propiedades SET nombre = 'Búsqueda Nora (Tito)', direccion = 'Uruguay 807, C1015ABQ Cdad. Autónoma de Buenos Aires' WHERE id = '10196';
UPDATE propiedades SET nombre = 'Malabia 2221', direccion = 'Malabia 2221, C1425EZE Cdad. Autónoma de Buenos Aires' WHERE id = '10197';
UPDATE propiedades SET nombre = 'Av. Cabildo 4268 1D', direccion = 'Av. Cabildo 4268, C1429ABN Cdad. Autónoma de Buenos Aires' WHERE id = '10198';
UPDATE propiedades SET nombre = 'Tucuman 766 (Venta)', direccion = 'Tucumán 766, C1049AAP Cdad. Autónoma de Buenos Aires' WHERE id = '10199';
UPDATE propiedades SET nombre = 'Local Uruguay 1134 (2do alquiler)', direccion = 'Uruguay 1134, Cdad. Autónoma de Buenos Aires' WHERE id = '10200';
UPDATE propiedades SET nombre = 'Olleros 3540 (Marce)', direccion = 'Olleros 3540, C1427EEB Cdad. Autónoma de Buenos Aires, Argentina' WHERE id = '10201';
UPDATE propiedades SET nombre = 'Uruguay 750 1C', direccion = 'Uruguay 750, C1015 ABP, Cdad. Autónoma de Buenos Aires' WHERE id = '10202';
UPDATE propiedades SET nombre = 'Washington 2810 7D', direccion = 'Washington 2810, C1430EUH Cdad. Autónoma de Buenos Aires' WHERE id = '10203';
UPDATE propiedades SET nombre = 'Guemes 4730 6A', direccion = 'Güemes 4730, C1425 Cdad. Autónoma de Buenos Aires' WHERE id = '10204';
UPDATE propiedades SET nombre = 'Cordoba 966 3°A - VENTA!', direccion = 'Av. Córdoba 966, C1054 Cdad. Autónoma de Buenos Aires' WHERE id = '10205';
UPDATE propiedades SET nombre = 'Av. Corrientes 818 dept1305', direccion = 'Av. Corrientes 818, caba' WHERE id = '10206';
UPDATE propiedades SET nombre = 'Azcuénaga 764', direccion = 'Azcuénaga 764, CABA' WHERE id = '10207';
UPDATE propiedades SET nombre = 'Santa Fe 2630, 11°E', direccion = 'Av. Sta. Fe 2630, C1425BGO Cdad. Autónoma de Buenos Aires' WHERE id = '10208';
UPDATE propiedades SET nombre = 'Salguero 1391 PB B', direccion = 'Salguero 1391, CABA' WHERE id = '10209';
UPDATE propiedades SET nombre = 'Florida 878 piso 12', direccion = 'Florida 878 , CABA' WHERE id = '10210';
UPDATE propiedades SET nombre = 'Alejandro Korn 4427', direccion = NULL WHERE id = '10211';
UPDATE propiedades SET nombre = 'Córdoba 744 piso 4', direccion = 'Av. Cordoba 744, CABA' WHERE id = '10212';
UPDATE propiedades SET nombre = ' Arenales 2832', direccion = 'Arenales 2832, CABA' WHERE id = '10213';
UPDATE propiedades SET nombre = 'Sarmiento 2338 piso 4  15', direccion = 'Sarmiento 2338, CABA' WHERE id = '10214';
UPDATE propiedades SET nombre = 'Scalabrini Ortiz 2416 piso 3', direccion = 'Scalabrini Ortiz 2416, CABA' WHERE id = '10215';
UPDATE propiedades SET nombre = 'Esmeralda 800', direccion = 'Esmeralda 827, C1007ABI Cdad. Autónoma de Buenos Aires' WHERE id = '10216';
UPDATE propiedades SET nombre = 'Busqueda Guillermo Svark', direccion = 'Buenos Aires, Argentina' WHERE id = '10217';
UPDATE propiedades SET nombre = 'Busqueda Depto Mariano', direccion = 'Buenos Aires, Argentina' WHERE id = '10218';
UPDATE propiedades SET nombre = 'Cordoba 966 3°A - ALQUILER!', direccion = 'Av. Córdoba 966, C1054 Cdad. Autónoma de Buenos Aires' WHERE id = '10219';
UPDATE propiedades SET nombre = 'Corrientes 900', direccion = 'Corrientes 900, CABA' WHERE id = '10220';
UPDATE propiedades SET nombre = 'Montañeses 2342 414', direccion = 'Montañeses 2342, CABA' WHERE id = '10221';
UPDATE propiedades SET nombre = 'Montañeses 2342 216', direccion = 'Montañeses 2342, CABA' WHERE id = '10222';
UPDATE propiedades SET nombre = 'Larrea 1257/59', direccion = 'Larrea 1259, CABA' WHERE id = '10223';
UPDATE propiedades SET nombre = 'Ecuador 1418', direccion = 'Ecuador 1418, CABA' WHERE id = '10224';
UPDATE propiedades SET nombre = 'Vidt 2056', direccion = 'Vidt 2056, CABA' WHERE id = '10225';
UPDATE propiedades SET nombre = 'Entre Ríos 1330', direccion = 'Entre Ríos 1330, CABA' WHERE id = '10226';
UPDATE propiedades SET nombre = 'Gallo 1435', direccion = 'Gallo 1435, CABA' WHERE id = '10227';
UPDATE propiedades SET nombre = 'Estados Unidos 1699', direccion = 'Estados Unidos 1699, C1101ABG Cdad. Autónoma de Buenos Aires' WHERE id = '10228';
UPDATE propiedades SET nombre = 'Villafañe 1451 3ro C', direccion = 'Villafañe 1451 , CABA' WHERE id = '10229';
UPDATE propiedades SET nombre = 'Esmeralda 740 4to (venta)', direccion = 'Esmeralda 740, CABA' WHERE id = '10230';
UPDATE propiedades SET nombre = 'Monroe 4050 5B', direccion = 'Monroe 4050, CABA' WHERE id = '10231';
UPDATE propiedades SET nombre = 'Busqueda Depto Mariano 2', direccion = 'Av. Córdoba 807, C1054AAH Cdad. Autónoma de Buenos Aires' WHERE id = '10232';
UPDATE propiedades SET nombre = 'Paseo Colón 71', direccion = 'Av. Paseo Colón 71, C1064 Cdad. Autónoma de Buenos Aires' WHERE id = '10233';
UPDATE propiedades SET nombre = 'Alsina 1928, 3°F', direccion = 'Adolfo Alsina 1928, C1090AAB Cdad. Autónoma de Buenos Aires' WHERE id = '10235';
UPDATE propiedades SET nombre = 'Búsqueda Alejandro Salazar (Ecuador)', direccion = 'Av. Córdoba 807, C1054AAH Cdad. Autónoma de Buenos Aires' WHERE id = '10236';
UPDATE propiedades SET nombre = 'Díaz Vélez 4170 4°C', direccion = 'Av. Díaz Vélez 4170, C1200AAV Cdad. Autónoma de Buenos Aires' WHERE id = '10237';
UPDATE propiedades SET nombre = 'Búsqueda Sebastían (Suarez)', direccion = 'Av. Córdoba 807, C1054AAH Cdad. Autónoma de Buenos Aires' WHERE id = '10238';
UPDATE propiedades SET nombre = 'Cochera Vidt 1947', direccion = 'Vidt 1947, C1425DJG Cdad. Autónoma de Buenos Aires' WHERE id = '10239';
UPDATE propiedades SET nombre = 'Búsqueda Ciampa (NQN)', direccion = 'Av. Córdoba 807, C1054AAH Cdad. Autónoma de Buenos Aires' WHERE id = '10240';
UPDATE propiedades SET nombre = 'Colombres 192', direccion = 'Colombres 192, C1177 Cdad. Autónoma de Buenos Aires' WHERE id = '10241';
UPDATE propiedades SET nombre = 'Castañares 5986', direccion = 'Av. Castañares 5986, C1439 Cdad. Autónoma de Buenos Aires' WHERE id = '10242';
UPDATE propiedades SET nombre = 'Carlos Melo 1816, Florida', direccion = 'Carlos Francisco Melo 1816, B1602CWH Florida, Provincia de Buenos Aires' WHERE id = '10243';
UPDATE propiedades SET nombre = 'Warnes 385 6°A', direccion = 'Warnes 385, C1414 Villa Crespo, Cdad. Autónoma de Buenos Aires' WHERE id = '10244';
UPDATE propiedades SET nombre = 'J. Salguero 1496 - VENTA', direccion = 'Jerónimo Salguero 1496, C1177AFB Cdad. Autónoma de Buenos Aires' WHERE id = '10245';
UPDATE propiedades SET nombre = 'Avenida de Mayo 1430 4to', direccion = 'Avenida de Mayo 1430, CABA' WHERE id = '10246';
UPDATE propiedades SET nombre = 'Arenales 1805 17°F', direccion = 'Arenales 1805, CABA' WHERE id = '10247';
UPDATE propiedades SET nombre = 'Dorrego 2765 16 B', direccion = 'Av. Dorrego 2765, C1425 Cdad. Autónoma de Buenos Aires' WHERE id = '10248';
UPDATE propiedades SET nombre = 'Complejo Venice Goletas 1 Depto.1205', direccion = 'Solís y Río Luján, Solís 1, B1648 Tigre, Provincia de Buenos Aires' WHERE id = '10249';
UPDATE propiedades SET nombre = 'Arenales 2330, 6°A', direccion = NULL WHERE id = '10250';
UPDATE propiedades SET nombre = 'Corrientes 951 2doD', direccion = 'Avenida Corrientes 951, CABA' WHERE id = '10251';
UPDATE propiedades SET nombre = 'Corrientes 951 2doE', direccion = 'Avenida Corrientes 951, CABA' WHERE id = '10252';
UPDATE propiedades SET nombre = 'Corrientes 951 2doF', direccion = 'Avenida Corrientes 951, CABA' WHERE id = '10253';
UPDATE propiedades SET nombre = 'Brasil 835', direccion = 'Brasil 835, caba' WHERE id = '10255';
UPDATE propiedades SET nombre = 'Uruguay 390 piso 19', direccion = 'Uruguay 390, CABA' WHERE id = '10256';
UPDATE propiedades SET nombre = 'Esmeralda 736', direccion = 'Esmeralda 736, CABA' WHERE id = '10257';
UPDATE propiedades SET nombre = 'Laprida 1900 PB-B', direccion = 'Laprida 1900, CABA' WHERE id = '10258';
UPDATE propiedades SET nombre = 'Diego Palma 100 San Isidro', direccion = 'Diego Palma 100 San Isidro' WHERE id = '10259';
UPDATE propiedades SET nombre = 'Búsqueda Marianito venta Venice', direccion = 'Av. Córdoba 807, C1054AAH Cdad. Autónoma de Buenos Aires' WHERE id = '10260';
UPDATE propiedades SET nombre = 'Rivadavia 6279 1F', direccion = 'Av. Rivadavia 6279, C1406GLF Cdad. Autónoma de Buenos Aires' WHERE id = '10261';
UPDATE propiedades SET nombre = 'Amenabar 2667 1ro "B" (Alq. 2026)', direccion = 'Amenábar 2667, C1428CQQ Cdad. Autónoma de Buenos Aires' WHERE id = '10262';
UPDATE propiedades SET nombre = 'Av. Córdoba 643 Loc y Ofi', direccion = 'Av. Córdoba 643, C1054 Cdad. Autónoma de Buenos Aires' WHERE id = '10263';
UPDATE propiedades SET nombre = 'Virrey Loreto 1627', direccion = 'Virrey Loreto 1627, CABA' WHERE id = '10264';
UPDATE propiedades SET nombre = 'Galpón Magallanes 2808 R. Escalada', direccion = 'Magallanes 2808, B1826AXW Remedios de Escalada, Provincia de Buenos Aires' WHERE id = '10265';
UPDATE propiedades SET nombre = 'Larrea 1021', direccion = 'Larrea 1021, CABA' WHERE id = '10266';
UPDATE propiedades SET nombre = 'Lope de Vega 1171 2A', direccion = 'Av. Lope de Vega 1171, C1407BNK Cdad. Autónoma de Buenos Aires' WHERE id = '10267';
UPDATE propiedades SET nombre = 'Lope de Vega 1171 2B', direccion = 'Av. Lope de Vega 1171, C1407BNK Cdad. Autónoma de Buenos Aires' WHERE id = '10268';
UPDATE propiedades SET nombre = 'Lope de Vega 1171 7B', direccion = 'Av. Lope de Vega 1171, C1407BNK Cdad. Autónoma de Buenos Aires' WHERE id = '10269';
UPDATE propiedades SET nombre = 'Migueletes 2306 2A', direccion = 'Migueletes 2306, C1428ASL Cdad. Autónoma de Buenos Aires' WHERE id = '10270';
UPDATE propiedades SET nombre = 'Migueletes 2306 3A', direccion = 'Migueletes 2306, C1428ASL Cdad. Autónoma de Buenos Aires' WHERE id = '10271';
UPDATE propiedades SET nombre = 'Migueletes 2306 4B', direccion = 'Migueletes 2306, C1428ASL Cdad. Autónoma de Buenos Aires' WHERE id = '10272';
UPDATE propiedades SET nombre = 'Migueletes 2306 9A', direccion = 'Migueletes 2306, C1428ASL Cdad. Autónoma de Buenos Aires' WHERE id = '10273';
UPDATE propiedades SET nombre = 'Av. Cabildo 1672 (Loc.Avenida)', direccion = 'CGRR+48 Buenos Aires, Cdad. Autónoma de Buenos Aires' WHERE id = '10274';
UPDATE propiedades SET nombre = 'Av. Cabildo 1672 (Loc.Galería)', direccion = 'CGRR+48 Buenos Aires, Cdad. Autónoma de Buenos Aires' WHERE id = '10275';
UPDATE propiedades SET nombre = 'Julian Alvarez 1449 7° (UF187)', direccion = 'Julián Álvarez 1449, C1414DSC Cdad. Autónoma de Buenos Aires' WHERE id = '10276';
UPDATE propiedades SET nombre = 'Casa Flaco', direccion = NULL WHERE id = '10277';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10278';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10279';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10280';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10281';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10282';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10283';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10284';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10285';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10286';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10287';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10288';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10289';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10290';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10291';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10292';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10293';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10294';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10295';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10296';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10297';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10298';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10299';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10300';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10301';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10302';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10303';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10304';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10305';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10306';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10307';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10308';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10309';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10310';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10311';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10312';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10313';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10314';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10315';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10316';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10317';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10318';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10319';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10320';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10321';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10322';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10323';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10324';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10325';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10326';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10327';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10328';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10329';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10330';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10331';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10332';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10333';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10334';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10335';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10336';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10337';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10338';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10339';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10340';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10341';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10342';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10343';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10344';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10345';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10346';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10347';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10348';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10349';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10350';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10351';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10352';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10353';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10354';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10355';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10356';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10357';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10358';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10359';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10360';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10361';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10362';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10363';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10364';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10365';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10366';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10367';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10368';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10369';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10370';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10371';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10372';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10373';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10374';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10375';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10376';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10377';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10378';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10379';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10380';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10381';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10382';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10383';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10384';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10385';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10386';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10387';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10388';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10389';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10390';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10391';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10392';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10393';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10394';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10395';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10396';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10397';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10398';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10399';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10400';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10401';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10402';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10403';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10404';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10405';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10406';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10407';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10408';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10409';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10410';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10411';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10412';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10413';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10414';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10415';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10416';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10417';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10418';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10419';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10420';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10421';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10422';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10423';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10424';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10425';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10426';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10427';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10428';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10429';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10430';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10431';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10432';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10433';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10434';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10435';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10436';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10437';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10438';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10439';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10440';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10441';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10442';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10443';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10444';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10445';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10446';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10447';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10448';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10449';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10450';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10451';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10452';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10453';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10454';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10455';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10456';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10457';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10458';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10459';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10460';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10461';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10462';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10463';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10464';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10465';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10466';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10467';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10468';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10469';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10470';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10471';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10472';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10473';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10474';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10475';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10476';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10477';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10478';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10479';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10480';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10481';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10482';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10483';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10484';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10485';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10486';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10487';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10488';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10489';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10490';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10491';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10492';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10493';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10494';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10495';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10496';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10497';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10498';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10499';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10500';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10501';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10502';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10503';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10504';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10505';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10506';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10507';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10508';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10509';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10510';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10511';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10512';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10513';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10514';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10515';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10516';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10517';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10518';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10519';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10520';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10521';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10522';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10523';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10524';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10525';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10526';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10527';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10528';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10529';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10530';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10531';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10532';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10533';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10534';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10535';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10536';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10537';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10538';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10539';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10540';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10541';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10542';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10543';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10544';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10545';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10546';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10547';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10548';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10549';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10550';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10551';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10552';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10553';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10554';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10555';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10556';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10557';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10558';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10559';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10560';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10561';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10562';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10563';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10564';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10565';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10566';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10567';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10568';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10569';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10570';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10571';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10572';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10573';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10574';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10575';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10576';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10577';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10578';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10579';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10580';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10581';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10582';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10583';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10584';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10585';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10586';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10587';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10588';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10589';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10590';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10591';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10592';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10593';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10594';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10595';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10596';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10597';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10598';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10599';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10600';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10601';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10602';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10603';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10604';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10605';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10606';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10607';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10608';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10609';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10610';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10611';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10612';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10613';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10614';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10615';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10616';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10617';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10618';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10619';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10620';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10621';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10622';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10623';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10624';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10625';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10626';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10627';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10628';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10629';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10630';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10631';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10632';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10633';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10634';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10635';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10636';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10637';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10638';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10639';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10640';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10641';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10642';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10643';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10644';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10645';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10646';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10647';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10648';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10649';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10650';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10651';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10652';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10653';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10654';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10655';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10656';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10657';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10658';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10659';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10660';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10661';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10662';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10663';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10664';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10665';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10666';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10667';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10668';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10669';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10670';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10671';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10672';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10673';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10674';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10675';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10676';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10677';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10678';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10679';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10680';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10681';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10682';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10683';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10684';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10685';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10686';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10687';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10688';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10689';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10690';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10691';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10692';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10693';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10694';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10695';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10696';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10697';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10698';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10699';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10700';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10701';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10702';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10703';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10704';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10705';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10706';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10707';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10708';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10709';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10710';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10711';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10712';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10713';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10714';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10715';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10716';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10717';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10718';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10719';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10720';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10721';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10722';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10723';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10724';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10725';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10726';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10727';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10728';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10729';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10730';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10731';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10732';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10733';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10734';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10735';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10736';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10737';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10738';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10739';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10740';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10741';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10742';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10743';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10744';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10745';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10746';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10747';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10748';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10749';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10750';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10751';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10752';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10753';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10754';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10755';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10756';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10757';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10758';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10759';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10760';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10761';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10762';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10763';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10764';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10765';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10766';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10767';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10768';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10769';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10770';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10771';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10772';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10773';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10774';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10775';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10776';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10777';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10778';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10779';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10780';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10781';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10782';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10783';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10784';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10785';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10786';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10787';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10788';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10789';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10790';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10791';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10792';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10793';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10794';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10795';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10796';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10797';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10798';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10799';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10800';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10801';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10802';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10803';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10804';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10805';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10806';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10807';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10808';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10809';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10810';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10811';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10812';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10813';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10814';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10815';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10816';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10817';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10818';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10819';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10820';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10821';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10822';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10823';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10824';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10825';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10826';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10827';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10828';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10829';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10830';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10831';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10832';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10833';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10834';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10835';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10836';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10837';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10838';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10839';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10840';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10841';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10842';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10843';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10844';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10845';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10846';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10847';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10848';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10849';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10850';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10851';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10852';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10853';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10854';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10855';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10856';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10857';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10858';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10859';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10860';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10861';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10862';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10863';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10864';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10865';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10866';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10867';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10868';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10869';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10870';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10871';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10872';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10873';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10874';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10875';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10876';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10877';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10878';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10879';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10880';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10881';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10882';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10883';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10884';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10885';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10886';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10887';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10888';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10889';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10890';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10891';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10892';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10893';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10894';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10895';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10896';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10897';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10898';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10899';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10900';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10901';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10902';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10903';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10904';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10905';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10906';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10907';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10908';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10909';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10910';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10911';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10912';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10913';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10914';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10915';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10916';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10917';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10918';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10919';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10920';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10921';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10922';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10923';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10924';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10925';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10926';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10927';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10928';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10929';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10930';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10931';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10932';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10933';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10934';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10935';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10936';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10937';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10938';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10939';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10940';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10941';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10942';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10943';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10944';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10945';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10946';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10947';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10948';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10949';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10950';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10951';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10952';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10953';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10954';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10955';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10956';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10957';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10958';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10959';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10960';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10961';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10962';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10963';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10964';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10965';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10966';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10967';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10968';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10969';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10970';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10971';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10972';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10973';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10974';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10975';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10976';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10977';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10978';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10979';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10980';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10981';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10982';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10983';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10984';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10985';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10986';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10987';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10988';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10989';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10990';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10991';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10992';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10993';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10994';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10995';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10996';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10997';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10998';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '10999';
UPDATE propiedades SET nombre = NULL, direccion = NULL WHERE id = '11000';